version: '3.4'

services:
  mysqldb:
    image: mysql
    container_name: mysqlcontainer
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: carStores
      MYSQL_USER: admin
      MYSQL_PASSWORD: Ayoscript222@
      MYSQL_ROOT_PASSWORD: Ayoscript222@
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/:rw  


  api:
    container_name: nodeAPI
    build:
      context: .
      target: development
    image: nodeapp:v1  
    ports:
      - 8080:8080
    expose:
       - 8080         
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules 
    depends_on:
      - mysqldb  
    command: npm run dev


volumes:
  my-db: