version: '3.8'

services:
  db:
    image: mysql
    container_name: mysqlService
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: Ayoscript222@
  api:
    depends_on:
      - db
    build:
      context: .
      target: development
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules 
    command: npm run dev

